image: docker:24.0.6

options:
  docker: true

pipelines:
  default:
    - step:
        name: Build, Push & Deploy to Local Minikube
        services:
          - docker
        script:
          # Install kubectl
          - apk add --no-cache curl bash
          - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          # Docker Hub login
          - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

          # Build & push playwright-k8 image
          - docker build -t $DOCKERHUB_USERNAME/playwright-k8:latest .
          - docker push $DOCKERHUB_USERNAME/playwright-k8:latest

          # Use kubeconfig from ngrok
          - echo "$KUBECONFIG_CONTENT" | base64 -d > kubeconfig
          - export KUBECONFIG=$(pwd)/kubeconfig

          # Update image in deployment OR create it
          - kubectl set image deployment/playwright-app playwright=$DOCKERHUB_USERNAME/playwright-k8:latest || kubectl apply -f deployment.yml

          # Wait for rollout
          - kubectl rollout status deployment/playwright-app
