apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allure-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard   # for Minikube use "standard"
