apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playwright-app
  template:
    metadata:
      labels:
        app: playwright-app
    spec:
      containers:
      - name: playwright
        image: dinesh571/playwright-k8:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: playwright-service
spec:
  type: NodePort
  selector:
    app: playwright-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
