apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test
spec:
  template:
    spec:
      containers:
      - name: playwright
        image: dinesh571/playwright:latest
        command: ["npx", "playwright", "test"]
        args:
          - "--shard=$(SHARD_ID)/$(TOTAL_SHARDS)"
          - "--workers=1"   # reduced from 4 → prevents overload
        env:
          - name: SHARD_ID
            value: "1"
          - name: TOTAL_SHARDS
            value: "4"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "3Gi"
      restartPolicy: Never
  backoffLimit: 0
