apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-{{SHARD_ID}}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: playwright
        image: {{DOCKER_IMAGE}}
        command: ["npx","playwright","test","--shard","{{SHARD_ID}}/{{TOTAL_SHARDS}}","--reporter","allure-playwright"]
        volumeMounts:
        - name: allure-results
          mountPath: $PVC_MOUNT_PATH
      volumes:
      - name: allure-results
        persistentVolumeClaim:
          claimName: allure-pvc

